---

- hosts: localhost
  connection: local
  become: true


  tasks:
    - name: install packages
      apt:
        name:
          - mc
          - python3-psutil
          - vim-nox
          - htop
          - tmux
